name: lincs
channels:
- conda-forge
dependencies:
- pip=21.0.1
- conda-forge::pandas=1.2
- conda-forge::tabulate=0.8.7
- conda-forge::jupyter=1.0.0
- conda-forge::ipykernel=5.1.0
- conda-forge::nb_conda_kernels=2.2.1
- conda-forge::widgetsnbextension=3.5.1
- conda-forge::jupyter_contrib_nbextensions=0.5.1
- conda-forge::matplotlib=3.1.3
- conda-forge::plotnine=0.6.0
- conda-forge::umap-learn=0.5.1
- conda-forge::rdkit=2019.09.3
- conda-forge::nb_black=1.0.7
- conda-forge::dvc=2.3.0
- conda-forge::dvc-s3=2.3.0
- conda-forge::r-base=3.5.1
- conda-forge::r-knitr=1.22
- conda-forge::r-rmarkdown=1.12
- conda-forge::r-tidyverse=1.3.0
- pip:
  - git+https://github.com/cytomining/pycytominer@838ac2eee8bee09b50a1ec8077201c01f7882c69
